# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example

  pgadmin4:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: elencristina91@hotmail.com
      PGADMIN_DEFAULT_PASSWORD: PgAdmin2019
    ports:
      - 16543:80
    depends_on:
      - db

